google:
  private_key: ${google_private_key}
  client_email: ${google_client_email}
  sheet_id: ${google_sheet_id}
  api_url: "https://www.googleapis.com/auth/spreadsheets"

whatsapp:
  web_url: "https://web.whatsapp.com/"
  group_name: "sheet-bot"
  is_archived: true

crawler:
  user_data_dir: "./user_data"

ai:
  is_enabled: true
  model_url: "http://127.0.0.1:11434/api/generate"
  model_name: "llama3.2"


